sonar.projectKey=JAlorL_Entitlement-system
sonar.organization=jalorl

sonar.sources=src
sonar.exclusions=src/tests/**
sonar.tests=src/tests

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8